#!/usr/bin/env bash
set -euo pipefail

SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET_DIR="$SOURCE_DIR"
COPY_ENV=""
PROXY_BASE_URL=""
PROXY_API_KEY=""
FORCE_OVERWRITE=0

usage() {
  cat <<'EOF'
Usage: install_openclaw_skill.sh [options]

Prepare the bundled MySearch OpenClaw skill for local use.
This installer does not download remote runtime code and does not modify
other installed skills.

Options:
  --install-to DIR        Copy the skill bundle into DIR before finishing setup
  --copy-env FILE         Copy FILE to target .env with 0600 permissions
                          Optional. Prefer OpenClaw skill env injection instead.
  --proxy-base-url URL    Generate target .env with this MYSEARCH_PROXY_BASE_URL
                          (must be combined with --proxy-api-key)
  --proxy-api-key KEY     Generate target .env with this MYSEARCH_PROXY_API_KEY
                          (must be combined with --proxy-base-url)
  --force                 Overwrite an existing target .env
  -h, --help              Show this help

Notes:
  --copy-env and --proxy-* are mutually exclusive.
  Generated .env is written with 0600 permissions and contains only the two
  proxy keys (Tavily / Firecrawl / Exa will all reuse them via the proxy).

Examples:
  bash scripts/install_openclaw_skill.sh
  bash scripts/install_openclaw_skill.sh --install-to ~/.openclaw/skills/mysearch
  bash scripts/install_openclaw_skill.sh --copy-env ~/.config/mysearch.env
  bash scripts/install_openclaw_skill.sh \
    --install-to ~/.openclaw/workspace/skills/mysearch \
    --proxy-base-url https://search.example.com \
    --proxy-api-key mysp-XXXXXXXX
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --install-to)
      TARGET_DIR="${2:?missing dir}"
      shift 2
      ;;
    --copy-env)
      COPY_ENV="${2:?missing env path}"
      shift 2
      ;;
    --proxy-base-url)
      PROXY_BASE_URL="${2:?missing url}"
      shift 2
      ;;
    --proxy-api-key)
      PROXY_API_KEY="${2:?missing api key}"
      shift 2
      ;;
    --force)
      FORCE_OVERWRITE=1
      shift 1
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

# 互斥与配对校验
if [[ -n "$COPY_ENV" && ( -n "$PROXY_BASE_URL" || -n "$PROXY_API_KEY" ) ]]; then
  echo "Error: --copy-env and --proxy-* are mutually exclusive." >&2
  exit 2
fi
if [[ ( -n "$PROXY_BASE_URL" && -z "$PROXY_API_KEY" ) || ( -z "$PROXY_BASE_URL" && -n "$PROXY_API_KEY" ) ]]; then
  echo "Error: --proxy-base-url and --proxy-api-key must be supplied together." >&2
  exit 2
fi

copy_skill_bundle() {
  if [[ "$TARGET_DIR" == "$SOURCE_DIR" ]]; then
    return
  fi

  mkdir -p "$TARGET_DIR"
  tar -C "$SOURCE_DIR" \
    --exclude='.env' \
    --exclude='__pycache__' \
    -cf - . | tar -C "$TARGET_DIR" -xf -
}

prepare_env_file() {
  if [[ "$SOURCE_DIR/.env.example" != "$TARGET_DIR/.env.example" ]]; then
    install -m 0644 "$SOURCE_DIR/.env.example" "$TARGET_DIR/.env.example"
  fi

  local target_env="$TARGET_DIR/.env"

  if [[ -n "$COPY_ENV" ]]; then
    if [[ -e "$target_env" && "$FORCE_OVERWRITE" -ne 1 ]]; then
      echo "Refusing to overwrite existing $target_env (use --force to override)" >&2
      exit 1
    fi
    install -m 0600 "$COPY_ENV" "$target_env"
    return
  fi

  if [[ -n "$PROXY_BASE_URL" && -n "$PROXY_API_KEY" ]]; then
    if [[ -e "$target_env" && "$FORCE_OVERWRITE" -ne 1 ]]; then
      echo "Refusing to overwrite existing $target_env (use --force to override)" >&2
      exit 1
    fi
    # 用 install -m 0600 创建空文件，再写入；保证最终权限是 0600
    install -m 0600 /dev/null "$target_env"
    cat >"$target_env" <<EOF_ENV
# Auto-generated by install_openclaw_skill.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Tavily / Firecrawl / Exa will all be routed through this proxy by default.
MYSEARCH_PROXY_BASE_URL=$PROXY_BASE_URL
MYSEARCH_PROXY_API_KEY=$PROXY_API_KEY
EOF_ENV
    chmod 0600 "$target_env"
    echo "Wrote $target_env (0600) with MYSEARCH_PROXY_BASE_URL + MYSEARCH_PROXY_API_KEY"
  fi
}

copy_skill_bundle
prepare_env_file

cat <<EOF
MySearch OpenClaw skill is ready at: $TARGET_DIR

What changed:
1. Runtime is bundled inside the skill package
2. No remote downloads were performed
3. No other installed skills were modified

Next steps:
1. Prefer injecting env via OpenClaw skill config instead of copying secrets into the skill folder
2. Minimal trusted setup: MYSEARCH_PROXY_BASE_URL + MYSEARCH_PROXY_API_KEY
3. If you do not have a proxy yet, fall back to MYSEARCH_TAVILY_API_KEY + MYSEARCH_FIRECRAWL_API_KEY
4. Only use --copy-env or $TARGET_DIR/.env for local debugging
5. Run: python3 $TARGET_DIR/scripts/mysearch_openclaw.py health
EOF
